### ISSUE TITLE
Quantization, Pruning and distillation

### ISSUE THREAD

**Issue by seekingdeep** [liuch37/pan-pytorch#11]
.

**Comment by liuch37** [comment]
May I know what is your goal for your test detection project? For example, commercialize a product, own interest, academia research...etc?

**Comment by seekingdeep** [comment]
to include within the product perhaps, though i am currently only a single person.

**Comment by liuch37** [comment]
That sounds interesting. Since I am quite busy personally, I could do some consultant/prototype for you - with some random delay expected.

**Comment by seekingdeep** [comment]
i am interested in hiring you to deliver a complete code that is accurate, efficient and ready to be deployed.
select backbone > Quantization > train using gpu > pruning > finetune > export to onnx or pytorch lightning etc..> deploy on final devices Raspberry Pi to inference using cpu-only

**Comment by seekingdeep** [comment]
So what do you think?
