### ISSUE TITLE
How to evaluate the model?

### ISSUE THREAD

**Issue by suresh-s** [liuch37/pan-pytorch#14]
I have completed the training using the totaltext.  I want to evaluate the model to find the Prediction, Recall, F Score.

I have noticed the file "Deteval.py".  But I don't know how to use it and what are all the argument to be passed.

could you suggest me?

**Comment by liuch37** [comment]
Change the corresponding image/label paths in Deteval.py and run ```python Deteval.py```.

**Comment by suresh-s** [comment]
In Deteval.py, there are 4 fields.  

I have set values for following 2 fields.
gt_dir = project_root + 'data/totaltext/Groundtruth/Polygon/Test/'
img_root = project_root + 'data/totaltext/Images/Test/'

what should be assigned for following fields?
fid_path, input_dir

**Comment by liuch37** [comment]
fid_path is for storing your evaluarion scores, input_dir is your prediction results after running inference.

**Comment by suresh-s** [comment]
That means `python inference.py` should be executed before `python Deteval.py`.  is it correct?

I have executed inference.  but it failed. Below is the error trace.  Could you tell me what is the issue?

```
~/source/pan-pytorch# python inference.py --input ./data/totaltext/Images/Test --model ./outputs/model_epoch_1960.pth --bbox_type poly
Namespace(bbox_type='poly', gpu=False, input='./data/totaltext/Images/Test', model='./outputs/model_epoch_1960.pth', output='results', worker=4)
CPU being used!
Create dataset......
Length of test dataset is: 300
Create model......
Traceback (most recent call last):
  File "inference.py", line 95, in <module>
    model.load_state_dict(torch.load(trained_model_path, map_location=lambda storage, loc: storage), strict=False)
  File "/root/.virtualenvs/panplus_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for PAN:
	size mismatch for reduce_layer1.conv.weight: copying a param with shape torch.Size([128, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 64, 1, 1]).
	size mismatch for reduce_layer2.conv.weight: copying a param with shape torch.Size([128, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 128, 1, 1]).
	size mismatch for reduce_layer3.conv.weight: copying a param with shape torch.Size([128, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 256, 1, 1]).
	size mismatch for reduce_layer4.conv.weight: copying a param with shape torch.Size([128, 2048, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 512, 1, 1]).
```

**Comment by liuch37** [comment]
Make sure you are using the same backbone for the saved and inference model.

**Comment by suresh-s** [comment]
I have used the same backbone for Training and Inference since PAN has backbone.  both Training and and Inference uses the same PAN class's object

**Comment by liuch37** [comment]
Do you set ```neck_channel``` the same for both train.py and inference.py?

**Comment by suresh-s** [comment]
I have changed the neck_channel according to training neck_channel. Now error disappears.  But i got another error.  Could you help me to fix it?

```
~/source/pan-pytorch# python inference.py --input ./data/totaltext/Images/Test --model ./outputs/model_epoch_1960.pth --bbox_type poly 
Namespace(bbox_type='poly', gpu=False, input='./data/totaltext/Images/Test', model='./outputs/model_epoch_1960.pth', output='results', worker=4)
CPU being used!
Create dataset......
Length of test dataset is: 300
Create model......
Prediction on testset......
Testing 0/300
/root/.virtualenvs/panplus_env/lib/python3.6/site-packages/torch/nn/functional.py:2423: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "inference.py", line 115, in <module>
    det_res = get_results(det_out, data['img_metas'], min_area, min_score, bbox_type)
  File "/root/source/pan-pytorch/utils/helper.py", line 82, in get_results
    contours, _ = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE) # bug in official released code
ValueError: too many values to unpack (expected 2)
```

**Comment by liuch37** [comment]
Make sure you install opencv >= 4.0.0.

**Comment by suresh-s** [comment]
Now I can be able run the evaluation.

From the inference results at `results/submit_tt/*.txt`, i want to visualize the results on the image and check the quality of detection.  Is there any tool available to populate the result on the image?  and could you tell me the what is this comma separated integer means?

**Comment by suresh-s** [comment]
I am new to this field and independently learning. if you don't mind, could you help me to understand?   Is there any tool available to populate the result on the image? and could you tell me the what is this comma separated integer means?

**Comment by liuch37** [comment]
Those integers are [x1, y1, x2, y2...] for polygon points. You can check the function ```draw_result``` inside ```inference.py``` which is putting the predicted polygons on top of the images.

**Comment by aswa123** [comment]
@suresh-s  hello 
are you succeed to run Inference.py?
how did you do that?
