### ISSUE TITLE
How to evaluate the model? 

### ISSUE THREAD

**Issue by MustafaAlahmid** [liuch37/pan-pytorch#4]
I have trained the model on my own dataset which is the same as IC15, How can i evaluate the model or i want to check the output of the model on other set of images and desplay them ?

**Comment by liuch37** [comment]
Run inference.py you can get the model output on any dataset. It will be stored in txt files by using the function write_result. I havent checked ic15 evaluation, but you can try script.py in /eval/ic15. You need to change to write_result_ic15 in inference.py beforehand.
