### ISSUE TITLE
Backbone Resnet101 - Training time error

### ISSUE THREAD

**Issue by suresh-s** [liuch37/pan-pytorch#5]
I have changed the backbone to Resnet101 and started the training,

got the following error

"RuntimeError: Given groups=1, weight of size 128 64 1 1, expected input[8, 256, 160, 160] to have 64 channels, but got 256 channels instead"

Could you tell me the reason for this error?

**Comment by liuch37** [comment]
Can you provide more error info, e.g., which line in which files does it crash, training parameters used, how to build your model...etc?

**Comment by suresh-s** [comment]
Thank you for the quick response.

Error is showed on the line "`return self.relu(self.bn(self.conv(x)))`" on the file **"/root/source/pan-pytorch/models/fpem.py"**

Please find the complete error trace below

![image](https://user-images.githubusercontent.com/2168986/118081239-8f18b100-b3d8-11eb-917f-2be97038124d.png)

**Comment by liuch37** [comment]
Replace this ```neck_channel = (256, 512, 1024, 2048)``` in your train.py. This setting is for both ResNet50 and ResNet101.
